export const CIUDADES_JUJUY = [
  "San Salvador de Jujuy",
  "Palpalá",
  "Perico",
  "San Pedro de Jujuy",
  "El Carmen",
  "Monterrico",
  "Yuto",
  "Libertador General San Martín",
  "La Quiaca",
  "Humahuaca",
  "Tilcara",
  "San Antonio",
  "Fraile Pintado",
  "El Talar",
  "Caimancito",
  "Calilegua",
  "Maimará",
  "Purmamarca",
  "Volcán",
  "Susques",
  "Tumbaya",
  "Abra Pampa",
  "Aguas Calientes",
  "La Mendieta",
  "Valle Grande",
  "Termas de Reyes",
  "Yala",
  "Chalican",
  "El Aguilar",
  "Rinconada",
];
